<?php

return array(
  'xero_key' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_key',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Xero Key',
    'title' =>  'Xero Key',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'xero_secret' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_secret',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Xero Secret',
    'title' => 'Xero Secret',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'xero_public_certificate' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_public_certificate',
    'type' => 'Text',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Xero Public Certificate Path',
    'description' => 'Enter the full path to your public Certificate',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'xero_private_key' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_private_key',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Xero Private Key Path',
    'description' => 'Enter the full path to your private Key',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'xero_default_revenue_account' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_default_revenue_account',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'default' => 200,
    'title' => 'Xero Default Revenue Account',
    'description' => 'Account to code contributions to',
    'help_text' => 'For more complex rules you will need to add a custom extension',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'xero_invoice_number_prefix' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_invoice_number_prefix',
    'type' => 'String',
    'add' => '4.6',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Optionally define a string to prefix invoice numbers when pushing to Xero.',
    'title' =>  'Xero invoice number prefix',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'xero_push_contribution_status' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_push_contribution_status',
    'type' => 'Array',
    'add' => '4.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Select contribution status that can be pushed to Xero.',
    'title' =>  'Push Contribution Status',
    'help_text' => '',
    'html_type' => 'Select',
    'options' => CRM_Contribute_PseudoConstant::contributionStatus(NULL, 'name'),
    'html_attributes' => array(
      'multiple' => 1,
      'class' => 'crm-select2',
    ),
    'quick_form_type' => 'Select',
  ),
 );
