<?php

return array(
  'xero_key' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_key',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Xero Key',
    'title' =>  'Xero Key',
    'help_text' => '',
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
  ),
  'xero_secret' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_secret',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Xero Secret',
    'title' => 'Xero Secret',
    'help_text' => '',
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
  ),
  'xero_public_certificate' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_public_certificate',
    'type' => 'Text',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Xero Public Certificate Path',
    'description' => 'Enter the full path to your public Certificate',
    'help_text' => '',
    'html_type' => 'Text',
    'html_attributes' => array(
      'size' => 50,
    ),
    'quick_form_type' => 'Element',
  ),
  'xero_private_key' => array(
    'group_name' => 'Xero Settings',
    'group' => 'xero',
    'name' => 'xero_private_key',
    'type' => 'String',
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Xero Private Key Path',
    'description' => 'Enter the full path to your private Key',
    'help_text' => '',
    'html_type' => 'Text',
    'quick_form_type' => 'Element',
  ),
 );