<?php
use CRM_Civixero_ExtensionUtil as E;
/**
 * 
 * Controls page for handling OAuth 2.0 Authorization with Xero.
 * 
 * TODO: Refactor reusable functionality into a separate class.
 *
 */

class CRM_Civixero_Page_XeroAuthorize extends CRM_Core_Page {

  
  private $resourceOwnerURL = 'https://api.xero.com/api.xro/2.0/Organisation';
  
  private $connectionsURL = 'https://api.xero.com/connections';

  private $redirectURL;
  
  private $clientID;

  private $clientSecret;
  
  private $hasValidTokens = FALSE;
  
  private $tenantID;
  
  /**
   * 
   * @var []
   */
  private $accessTokenData;
  
  public $provider;


  private function init() {
    $this->clientID = trim(Civi::settings()->get('xero_client_id'));
    $this->clientSecret = trim(Civi::settings()->get('xero_client_secret'));
    $this->accessTokenData = Civi::settings()->get('xero_access_token');
    $this->tenantID = Civi::settings()->get('xero_tenant_id');
    $this->redirectURL = CRM_Utils_System::url('civicrm/xero/authorize',
      NULL, 
      TRUE,
      NULL,
      FALSE,
      FALSE,
      TRUE
    );
    $this->provider = new CRM_Civixero_OAuth2_Provider_Xero([
      'clientId' => trim(Civi::settings()->get('xero_client_id')),
      'clientSecret' => trim(Civi::settings()->get('xero_client_secret')),
      'redirectUri' => $this->redirectURL,
      ]    
    );
    $refresh_token = NULL;
    if (!empty($this->accessTokenData['refresh_token'])) {
      $access_token = new \League\OAuth2\Client\Token\AccessToken($this->accessTokenData);
      $refresh_token = $access_token->getRefreshToken();
    }
    // We may or may not have valid tokens at this point.
    // If we have a refresh token, test it by getting a new access token
    // and use them to get the tenant ID.
    if ($refresh_token) {
      try {
        $newAccessToken = $this->provider->getAccessToken('refresh_token', [
          'refresh_token' => $refresh_token,
        ]);
        // Save the new tokens.
        $refresh_token = $newAccessToken->getRefreshToken();
        if ($refresh_token) {
          $this->accessTokenData = $newAccessToken->jsonSerialize();
          $this->tenantID = $this->provider->getConnectedTenantID($newAccessToken->getToken());
          if ($this->tenantID) {
            Civi::settings()->set('xero_access_token', $this->accessTokenData);
            Civi::settings()->set('xero_tenant_id', $this->tenantID);
            $this->hasValidTokens = TRUE;
          }
        }
      }
      catch (Exception $e) {
        // Expected invalid_grant. Continue to let user authorize.
      }
    }
  }
  

  private function processAuthCode() { 
    // Have we been redirected back from an authorization?
    $code = CRM_Utils_Array::value('code', $_GET, '');
    $state = CRM_Utils_Array::value('state', $_GET, '');
    if ($code) {
      // Check state to mitigate against CSRF attacks.
      if ($state != $this->getState()) {
        throw new Exception('Invalid state.');
      }
      
      // Try to get an access token using the authorization code grant.
      $token = $this->provider->getAccessToken('authorization_code', [
        'code' => $code
      ]);
      // The refresh token and tenant_id
      // are required to get new access tokens without
      // needing the user to authorize again.
      $refresh_token = $token->getRefreshToken();
      $access_token = $token->getToken();
      $success = FALSE;
      if ($access_token && $refresh_token) {
        // The tenant_id is also required.
        $tenant_id = $this->provider->getConnectedTenantID($access_token);
        if ($tenant_id) {
          // Save to Settings.
          Civi::settings()->add([
            'xero_access_token' => $token->jsonSerialize(),
            'xero_tenant_id' => $tenant_id,
            ]
           );
         // Signal success.
          $success = TRUE;
          CRM_Core_Session::setStatus(E::ts('Xero Authorization Successful'));
          // Redirect to clear stale $_GET params.
          CRM_Utils_System::redirect('/' . CRM_Utils_System::currentPath(), 'reset=1');
        }
      }
      if (!$success) {
        CRM_Core_Session::setStatus(E::ts('Xero Authorization Not Successful, try again.'));
        CRM_Core_Error::debug_var('XeroAuthorization Error', [
          'token' => $token->jsonSerialize(), 
          'tenant_id' => $tenant_id,
        ]);
      }
    }
  }

  /**
   * Gets the URL to authorize with Xero.
   * 
   * @return string
   */
  public function getAuthURL() {
    $options = [
      'state' => $this->getState(), // If empty, the provider will generate one.
    ];    
    $url = $this->provider->getAuthorizationUrl($options);
    // The state is used to verify the response.
    // Store the state generated by the OAuth provider object.
    $this->setState($this->provider->getState());
    return $url;
  }
 
  /**
   * Gets the state used during  authorization.
   * @return string
   */
  protected function getState() {
    return CRM_Core_Session::singleton()->get('oauth2state', 'xero'); 
  }
  
  /**
   * Stores the state used during authorization.
   * 
   * @param string $state
   */
  protected function setState($state = NULL) {
    CRM_Core_Session::singleton()->set('oauth2state', $state, 'xero'); 
  }
  

  public function run() {
    $this->init();
    $page_content = '';
    //Check if we have returned from authorization and process data.
    // Do we have a client id
    $link_label = E::ts('Authorize with Xero');
    if (empty($this->clientID) || empty($this->clientSecret)) {
      // Set status
      $page_content = "A Client ID needs to be added in the Xero Settings.";
    }
    else {
      $this->processAuthCode();
      if ($this->hasValidTokens) {
        $status_msg = '<strong>' . E::ts("CiviCRM can connect to Xero. You do not need to authorize again at this point.") . '</strong>';
        $link_label = E::ts('Change Authorized user');
      }
      else {
        $status_msg = E::ts('You will need to Authorize with Xero by clicking the link below.');
        
      }
      $page_content = '<p>' . $status_msg . '</p>';
      $url = $this->getAuthURL();
      $page_content .= '<a class="button" href="' . $url . '">' . $link_label . '</a>';
    }
    $this->assign('authorizeLink', $page_content);

    parent::run();
  }

}
